apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wenit-node-express-seed-tls
  namespace: wenit
spec:
  secretName: wenit-node-express-seed-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wenit-node-express-seed.wenit.com.br
  dnsNames:
  - wenit-node-express-seed.wenit.com.br
  acme:
    config:
    - http01:
        ingress: wenit-node-express-seed
      domains:
      - wenit-node-express-seed.wenit.com.br
